version: "3"
services:
  BijouBrocUiDev:
    image: node:latest
    container_name: DevBijouBrocUi
    working_dir: /app
    restart: always
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=production
    expose:
      - 8080
    networks:
      - bijoubroc
      - weebo
    command: "yarn static"
networks:
  bijoubroc:
    name: bijoubroc
  weebo:
    name: weebo
